#
# Majority of this code is adapted from that in Rstudio's
#   shinydashboard package
#

# Add dependencies
#' @importFrom htmltools htmlDependency htmlDependencies
appendDependencies <- function(x, value) {
  if (inherits(value, "html_dependency"))
    value <- list(value)

  old <- attr(x, "html_dependencies", TRUE)

  htmlDependencies(x) <- c(old, value)
  x
}

# Add dashboard dependencies to a tag object
addDeps <- function(x) {

  dashboardDeps <- list(
    htmlDependency(
      name = "appcss",
      version = packageVersion("radminkit"),
      src = system.file("inst/css", package = "radminkit"),
      stylesheet = "radminkit.min.css"
    ),
    htmlDependency(
      name = "appjs",
      version = packageVersion("radminkit"),
      src = system.file("inst/js", package = "radminkit"),
      script = "radminkit.min.js"
    )
  )

  appendDependencies(x, dashboardDeps)
}

#' Assert that a tag has specified properties
#' @param tag A tag object.
#' @param type The type of a tag, like "div", "a", "span".
#' @param class An HTML class.
#' @param allowUI If TRUE (the default), allow dynamic outputs generated by
#'   \code{\link[shiny]{uiOutput}} or \code{\link[shiny]{htmlOutput}}. When a
#'   dynamic output is provided, \code{tagAssert} won't try to validate the the
#'   contents.
#' @keywords internal
tagAssert <- function(tag, type = NULL, class = NULL, allowUI = TRUE) {
  if (!inherits(tag, "shiny.tag")) {
    print(tag)
    stop("Expected an object with class 'shiny.tag'.")
  }

  # Skip dynamic output elements
  if (allowUI &&
      (hasCssClass(tag, "shiny-html-output") ||
       hasCssClass(tag, "shinydashboard-menu-output"))) {
    return()
  }

  if (!is.null(type) && !tag$name %in% type) {
    stop("Expected tag to be of type ", type)
  }

  if (!is.null(class)) {
    if (is.null(tag$attribs$class)) {
      stop("Expected tag to have class '", class, "'")

    } else {
      # tagClasses <- strsplit(tag$attribs$class, " ")[[1]]
      # if (!(class %in% tagClasses)) {
      if (class != tag$attribs$class) {
        stop("Expected tag to have class '", class, "'")
      }
    }
  }
}

# Return TRUE if a shiny.tag object has a CSS class, FALSE otherwise.
hasCssClass <- function(tag, class) {
  if (is.null(tag$attribs) || is.null(tag$attribs$class))
    return(FALSE)

  classes <- strsplit(tag$attribs$class, " +")[[1]]
  return(class %in% classes)
}

# Make sure a tab name is valid (there's no "." in it).
validateTabName <- function(name) {
  if (grepl(".", name, fixed = TRUE)) {
    stop("tabName must not have a '.' in it.")
  }
}

# Valid badge options
validBadges <- c(
  "primary", "secondary",
  "success", "danger",
  "warning", "info",
  "light", "dark"
)

# Append to an element's class
addClass <- function(element, append) {
  return(paste(c(element, append), collapse = " "))
}

#' #' @export
#' addJsDeps <- function() {
#'   includeScript(system.file("jquery-ui/jquery-ui.min.js", package = "dattaableR"))
#'   includeScript(system.file("js/vendor-all.min.js", package = "dattaableR"))
#'   includeScript(system.file("bootstrap-4.5.2/popover.js", package = "dattaableR"))
#'   includeScript(system.file("bootstrap-4.5.2/bootstrap.min.js", package = "dattaableR"))
#'   includeScript(system.file("js/pcoded.min.js", package = "dattaableR"))
#' }
